/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Kel
 */
public class fr_ppal extends javax.swing.JFrame {
    private Dimension dim;
    /**
     * Creates new form fr_ppal
     */
    public fr_ppal() {
        initComponents();
        dim = super.getToolkit().getScreenSize();
        super.setExtendedState(MAXIMIZED_BOTH);
        super.setVisible(true);
        jToolBar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        MenuPrincipal = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        Modulos = new javax.swing.JMenu();
        Inventario = new javax.swing.JMenu();
        Procesos_Inv = new javax.swing.JMenu();
        Entrada_Salida = new javax.swing.JMenuItem();
        Tabla_Inv = new javax.swing.JMenu();
        Articulo = new javax.swing.JMenuItem();
        Colores = new javax.swing.JMenuItem();
        Unidades = new javax.swing.JMenuItem();
        Categoria = new javax.swing.JMenuItem();
        SubCategoria = new javax.swing.JMenuItem();
        Almacenes = new javax.swing.JMenuItem();
        Reporte_Inv = new javax.swing.JMenu();
        Compras = new javax.swing.JMenu();
        Procesos_CxC = new javax.swing.JMenu();
        Tabla_CxC = new javax.swing.JMenu();
        Reporte_CxC = new javax.swing.JMenu();
        Ventas = new javax.swing.JMenu();
        Procesos_CxP = new javax.swing.JMenu();
        Tabla_CxP = new javax.swing.JMenu();
        Reporte_CxP = new javax.swing.JMenu();
        Contabilidad = new javax.swing.JMenu();
        Soporte = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search44.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_add.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3floppy_unmount.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_cancel.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_remove.png"))); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2leftarrow.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1leftarrow.png"))); // NOI18N
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1rightarrow.png"))); // NOI18N
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2rightarrow.png"))); // NOI18N
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kfm_home.png"))); // NOI18N
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton11);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        Archivo.setText("Archivo");
        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Archivo.add(Salir);

        MenuPrincipal.add(Archivo);

        Edicion.setText("Edicion");
        MenuPrincipal.add(Edicion);

        Modulos.setText("Modulos");
        Modulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModulosMouseClicked(evt);
            }
        });

        Inventario.setText("Inventario");

        Procesos_Inv.setText("Procesos");

        Entrada_Salida.setText("Entrada y Salida");
        Procesos_Inv.add(Entrada_Salida);

        Inventario.add(Procesos_Inv);

        Tabla_Inv.setText("Tablas");

        Articulo.setText("Articulos o Productos");
        Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticuloActionPerformed(evt);
            }
        });
        Tabla_Inv.add(Articulo);

        Colores.setText("Colores");
        Tabla_Inv.add(Colores);

        Unidades.setText("Unidades");
        Tabla_Inv.add(Unidades);

        Categoria.setText("Categoria o Linea");
        Tabla_Inv.add(Categoria);

        SubCategoria.setText("SubCategoria o Sublinea");
        Tabla_Inv.add(SubCategoria);

        Almacenes.setText("Almacenes");
        Tabla_Inv.add(Almacenes);

        Inventario.add(Tabla_Inv);

        Reporte_Inv.setText("Reportes");
        Inventario.add(Reporte_Inv);

        Modulos.add(Inventario);

        Compras.setText("CxC");

        Procesos_CxC.setText("Procesos");
        Compras.add(Procesos_CxC);

        Tabla_CxC.setText("Tablas");
        Compras.add(Tabla_CxC);

        Reporte_CxC.setText("Reportes");
        Compras.add(Reporte_CxC);

        Modulos.add(Compras);

        Ventas.setText("CxP");

        Procesos_CxP.setText("Procesos");
        Ventas.add(Procesos_CxP);

        Tabla_CxP.setText("Tablas");
        Ventas.add(Tabla_CxP);

        Reporte_CxP.setText("Reportes");
        Ventas.add(Reporte_CxP);

        Modulos.add(Ventas);

        Contabilidad.setText("Contabilidad");
        Modulos.add(Contabilidad);

        MenuPrincipal.add(Modulos);

        Soporte.setText("Soporte");
        MenuPrincipal.add(Soporte);

        Ayuda.setText("Ayuda");
        MenuPrincipal.add(Ayuda);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1358, Short.MAX_VALUE)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ArchivoActionPerformed

    private void ModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModulosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModulosMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        int salir = JOptionPane.showConfirmDialog(null,"Desea Salir del Sistema?");
        
        if(salir==0){
            System.exit(0);
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticuloActionPerformed
        // TODO add your handling code here:
        fr_productos prod = new fr_productos();
        escritorio.add(prod);
        prod.show();
    }//GEN-LAST:event_ArticuloActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_ppal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_ppal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Almacenes;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Articulo;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenuItem Categoria;
    private javax.swing.JMenuItem Colores;
    private javax.swing.JMenu Compras;
    private javax.swing.JMenu Contabilidad;
    private javax.swing.JMenu Edicion;
    private javax.swing.JMenuItem Entrada_Salida;
    private javax.swing.JMenu Inventario;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenu Modulos;
    private javax.swing.JMenu Procesos_CxC;
    private javax.swing.JMenu Procesos_CxP;
    private javax.swing.JMenu Procesos_Inv;
    private javax.swing.JMenu Reporte_CxC;
    private javax.swing.JMenu Reporte_CxP;
    private javax.swing.JMenu Reporte_Inv;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu Soporte;
    private javax.swing.JMenuItem SubCategoria;
    private javax.swing.JMenu Tabla_CxC;
    private javax.swing.JMenu Tabla_CxP;
    private javax.swing.JMenu Tabla_Inv;
    private javax.swing.JMenuItem Unidades;
    private javax.swing.JMenu Ventas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    public static javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
